extends "res://tests/long_session_soak_test.gd"

## Headless visible-renderer audit for lifecycle-dependent phantom geometry and
## flashing materials/lights (ROADMAP Phase 10 §1).
##
## `long_session_soak_test.gd` drives the same production `Main` through real
## sortie cycles and proves the *counters* stay flat. Flat counters are not the
## same claim as a clean frame: the recorded defect this item exists for was a
## dormant `HeroDamagePresentation/DamageSparks` renderer that stayed *visible*
## across states and filled the screen with a warm flash while every node count
## stayed exactly where it started. This suite therefore reuses that soak's
## production drive and asks the other question — what is actually being drawn?
##
## Each cycle reaches six rest states and, at each of them, snapshots the live
## visible renderer set walked from the scene-tree root (destruction effects are
## deliberately detached into the tree root by `HeroDamagePresentation`, so a
## walk rooted at `Main` would miss exactly the class of phantom this audit is
## for):
##
##   * every `GeometryInstance3D` with `is_visible_in_tree()`, with its AABB,
##     `cast_shadow`, `transparency`, and, for particle renderers, `emitting`;
##   * every `Light3D` with `visible_in_tree`, its energy, and the per-tick
##     energy series over two simulated seconds.
##
## Renderer AABBs are recorded in the frame of the nearest owning `HeroShip`
## when there is one, and in world space otherwise. A craft holding station in
## free flight drifts by millimetres; its own presentation moving with it is not
## a defect, while a presentation stranded in world space at the position a
## craft was destroyed at is exactly the defect being looked for, and that one
## has no ship ancestor to be measured against.
##
## The rest states, in cycle order:
##
##   1. `on_foot_yard`            — player on foot at the yard, nothing running.
##   2. `activity_abandoned`      — a nearby-sector activity started and abandoned.
##   3. `cabin_bunk_returned`     — back in the pilot seat after leaving the seat
##                                  into the in-flight cabin, sleeping in a bunk,
##                                  waking, and retaking the seat.
##   4. `craft_parked`            — the craft at its berth and the pilot on foot,
##                                  reached by a real landing and disembark on
##                                  one cycle and by losing the craft in open
##                                  space and letting the berth regenerate it on
##                                  the next, because the same rest state reached
##                                  two ways has to draw the same frame.
##   5. `destroyed_regenerated`   — a parked craft damaged to critical, destroyed
##                                  and regenerated by its berth.
##   6. `after_reentry`           — whole-`Main` save, detach and re-entry.
##
## The central assertion is a cycle-to-cycle diff of the same state: after the
## warm-up cycle, the set of visible renderers at a state may not gain a single
## member, and no renderer that is visible in both may have moved in its own
## reference frame. That contract needs no hand-authored inventory of what the
## game draws — a phantom is precisely a renderer that is visible now and was
## not visible at the same rest state one cycle ago.
##
## Two more channels ride the same diff: the text of every world `Label3D` (a
## display's AABB is a function of the string it is showing, so the string is the
## readable form of "this display moved"), and each `ShipBerthFeedback`'s drawn
## lease glyphs against the lease state it publishes.
##
## Three same-cycle leak watches bracket the activity, the whole sortie and the
## destruction/regeneration with a before/after pair of walks, because a
## cross-cycle diff cannot see a phantom that was already there last cycle.
##
## Absolute contracts back the diff up, because a phantom that is already
## present in the warm-up cycle would diff clean against itself:
##
##   * no renderer whose name belongs to a transient damage/destruction/repair/
##     entry-heat channel may be *drawn* at rest — visible in tree, and either
##     opaque enough to see or, for a light, carrying energy above zero;
##   * no particle system anywhere in the tree may be `emitting` at rest;
##   * no visible light at rest may flash faster or deeper than the authored
##     reduced-flash contract allows.
##
## The flash thresholds are read off the production scripts, not invented:
##
##   * every light a production script declares `reduced_flash_safe` on is
##     declared so on the stated grounds that it "has no animation or process
##     path" (`scripts/world/habitat_spine.gd`,
##     `scripts/world/aft_junction_stack.gd`,
##     `scripts/world/ship_berth_feedback.gd`,
##     `scripts/ships/jovian_engineer_repair_presentation.gd`), matching the
##     `steady_no_flash` policy `scripts/ui/caption_presenter.gd`,
##     `scripts/ui/caption_accessibility_contract.gd` and `scripts/ui/hud.gd`
##     publish. So a `reduced_flash_safe` light that modulates at all is a
##     defect on its own declaration;
##   * the only ambient light modulation the station authors is
##     `ShipyardWorld._animate_warning_lights`, `base * (0.35 + 0.65 * max(0,
##     sin(elapsed * 3.8)))` — 3.8 rad/s is 0.605 Hz, at a modulation depth of
##     0.65 of peak. That is the authored ceiling for a light that is allowed to
##     move while the world is at rest;
##   * the only production lights authored to modulate faster are
##     `HeroDamagePresentation`'s `DamageWarningLight` (`sin(elapsed * 13)`,
##     2.07 Hz, and `sin(elapsed * 7)` at 1.11 Hz below critical) and
##     `EngineFailureLight` (`sin(elapsed * 29) + sin(elapsed * 61)`, 4.6 and
##     9.7 Hz), each of them from zero, so at full depth. Every one of those
##     belongs to a damage lifecycle that has to be over before the craft is at
##     rest.
##
## The rate estimator quantises to 0.25 Hz in a two-second window, so the rest
## ceiling is set one estimator step above the authored 0.605 Hz ambient and
## still sits well below the 1.11 Hz slowest damage cue.
##
## Environment:
##   KETH_PHANTOM_CYCLES=N   cycle count (default 4; the first two are warm-up).
##
## 174 s and 198 assertions at the default; 515 s and 872 at three times that.
## `docs/LIFECYCLE_PHANTOM_AUDIT.md` records what this found, fixed and accepted.

const HalyardTransport := preload("res://scripts/ships/halyard_crew_transport.gd")
const BunkInteraction := preload("res://scripts/interaction/ship_bunk.gd")

const DEFAULT_PHANTOM_CYCLES := 4
## Two cycles, for the same reason the long-session soak warms up for four: the
## first pass through a lifecycle builds presentation lazily. The Halyard's crew
## status readout, for one, ships from `_ready()` with a placeholder roster and
## only takes its live text once a pilot has actually been aboard, which moves
## that `Label3D`'s AABB exactly once in the life of the process.
const PHANTOM_WARM_UP_CYCLES := 2

const STATE_ON_FOOT_YARD: StringName = &"on_foot_yard"
const STATE_ACTIVITY_ABANDONED: StringName = &"activity_abandoned"
const STATE_CABIN_BUNK_RETURNED: StringName = &"cabin_bunk_returned"
const STATE_CRAFT_PARKED: StringName = &"craft_parked"
const STATE_DESTROYED_REGENERATED: StringName = &"destroyed_regenerated"
const STATE_AFTER_REENTRY: StringName = &"after_reentry"

const REST_STATES: Array[StringName] = [
	STATE_ON_FOOT_YARD,
	STATE_ACTIVITY_ABANDONED,
	STATE_CABIN_BUNK_RETURNED,
	STATE_CRAFT_PARKED,
	STATE_DESTROYED_REGENERATED,
	STATE_AFTER_REENTRY,
]

## Two simulated seconds of per-tick light energy, as the deliverable specifies.
const LIGHT_SERIES_SECONDS := 2.0
## Ticks of settling before a rest snapshot. Long enough for a retiring tween,
## a one-shot particle burst and a queued free to have finished; short enough
## that six of them per cycle stay inside the suite's time budget.
const REST_SETTLE_TICKS := 24
## Absolute light energy movement tolerated across the rest window. Renderer
## energies are authored as exact constants, so this is float noise only.
const REST_LIGHT_ENERGY_EPSILON := 0.001
## The authored ambient station pulse, `sin(_elapsed * 3.8)` in
## `ShipyardWorld._animate_warning_lights`, in hertz.
const AUTHORED_AMBIENT_FLASH_HZ := 3.8 / TAU
## Resolution of the turning-point rate estimator in a `LIGHT_SERIES_SECONDS`
## window: one extra turning point is half a period more.
const FLASH_RATE_RESOLUTION_HZ := 0.5 / LIGHT_SERIES_SECONDS
## A light may move at rest no faster than the authored ambient pulse, plus one
## estimator step. The slowest damage cue in production is 1.11 Hz, so this
## ceiling separates the two without touching the authored station lighting.
const MAX_REST_FLASH_HZ := AUTHORED_AMBIENT_FLASH_HZ + FLASH_RATE_RESOLUTION_HZ
## The authored ambient pulse's modulation depth, `0.65` of peak energy. Every
## production damage cue modulates from zero, at a depth of 1.0.
const MAX_REST_FLASH_DEPTH := 0.70
## Metres a renderer may move, in its own reference frame, between two cycles at
## the same rest state. A parked craft settles onto its pads within this.
const AABB_DRIFT_TOLERANCE := 0.05
## Reported diff lists are capped so one systemic regression cannot produce a
## megabyte of JSON per state.
const MAX_REPORTED_PATHS := 12
## Radius searched around the position a craft was destroyed at.
const DEATH_SITE_RADIUS := 40.0
## A renderer whose AABB moves by more than this inside a single rest window is
## an authored animation — a patrolling drone, a sweeping sensor head, a turning
## crane — not a resting one. The cycle-to-cycle position contract is applied to
## the renderers that hold still, because those are the ones whose position is a
## claim about where a lifecycle left them.
const WINDOW_MOTION_EPSILON := 0.002
## A renderer is only counted as drawn if something of it would actually reach
## the frame. `GeometryInstance3D.transparency` of 1.0 is fully transparent.
const DRAWN_TRANSPARENCY_LIMIT := 0.999

## Distance-selected LOD alternates. `ZenithAuthoredPresentation._apply_lod` and
## `TorrentHeroPresentation` swap a whole `LOD0`/`LOD1` group by camera distance
## with authored hysteresis, so which of the two is drawn is a function of where
## the camera is and where it came from — not of any lifecycle. Membership of
## these groups is therefore excluded from the visible-set diffs and reported on
## its own line; everything else about them (transient names, emission, position,
## flicker inside a rest window) is still audited exactly like any other
## renderer.
const LOD_ALTERNATE_MARKERS: Array[String] = ["/LOD0/", "/LOD1/"]

## Subtrees owned by a lifecycle presentation. A light inside one of these has to
## be steady at rest whatever its rate, because the lifecycle that drives it is
## over.
const LIFECYCLE_PATH_MARKERS: Array[String] = [
	"HeroDamagePresentation", "DamagePresentation", "DestructionEffects",
	"BerthFeedback", "RepairPresentation", "EntryEnvelope", "DustWash",
]

## Renderer names that belong to a transient lifecycle channel. Every one of
## these is created by a production presentation script for an impact, a
## destruction, a component failure, a repair cue, an atmospheric-entry overlay
## or a landing wash, and every one of them is over by the time the craft is at
## rest. Matched as a substring of the node name, because several are suffixed
## with a component id or a serial.
const TRANSIENT_RENDERER_NAMES: Array[String] = [
	# scripts/effects/hero_damage_presentation.gd — impacts and destruction.
	"HeroDamageImpact", "ImpactSparks", "ImpactFlash", "ImpactLight",
	"ComponentImpactBrace",
	"HeroDamageDestructionEffects", "ExplosionSparks", "ExplosionSmoke",
	"ExplosionFlash", "ExplosionCore", "ExplosionShockwave",
	"HeroHullDebris", "HullFragment", "FractureAfterglow",
	# scripts/effects/hero_damage_presentation.gd — persistent damage channels.
	"DamageSparks", "EngineFailureSparks", "EngineSmoke",
	"ComponentSparks", "ComponentSmoke", "ComponentGlow",
	"ComponentFailureShard", "ComponentRepair_",
	# scripts/ships/jovian_engineer_repair_presentation.gd — repair cues.
	"RepairArcSegment", "RepairWorkLamp",
	# scripts/effects/arrow_entry_exterior_envelope_presentation.gd and
	# scripts/effects/arrow_landing_dust_wash_presentation.gd — entry heat and
	# landing wash overlays.
	"EnvelopeSegments", "RecoveryRing", "EnvelopeMarker", "ShipLocalDustWash",
]

## Transient lights. Kept separate because a light is not a `GeometryInstance3D`
## and is audited through the light channel.
const TRANSIENT_LIGHT_NAMES: Array[String] = [
	"DamageWarningLight", "EngineFailureLight", "ImpactLight", "ExplosionFlash",
	"RepairWorkLight",
]

var _phantom_cycles := DEFAULT_PHANTOM_CYCLES
var _state_history: Dictionary = {}
var _state_records: Array[Dictionary] = []
var _phantom_failures := 0
var _cabin_bunk_round_trips := 0
var _destroyed_and_regenerated := 0
var _phantom_reentries := 0
var _states_snapshotted := 0
var _held_craft: HeroShip
var _held_craft_pose := Transform3D.IDENTITY
var _craft_without_damage_presentation_ids: Dictionary = {}
var _death_sites: Array[Vector3] = []
var _leak_watches := 0


func _run() -> void:
	_phantom_cycles = maxi(
		PHANTOM_WARM_UP_CYCLES + 1,
		_environment_int("KETH_PHANTOM_CYCLES", DEFAULT_PHANTOM_CYCLES)
	)
	_baseline_object_nodes = int(Performance.get_monitor(Performance.OBJECT_NODE_COUNT))

	var game := MAIN_SCENE.instantiate() as GameFlow
	_check(game != null, "production Main instantiates for the phantom-geometry audit")
	if game == null:
		_finish()
		return
	var filesystem := MemoryFilesystem.new()
	var isolated_store := Store.new(ISOLATED_STORE_PATH, filesystem)
	_check(
		game.configure_runtime_settings_persistence(
			isolated_store, "memory://lifecycle-phantom-legacy.cfg"
		),
		"the audit injects an isolated settings store before startup"
	)
	root.add_child(game)
	await process_frame
	await physics_frame
	await process_frame

	var player := game.get_node_or_null("Player") as PlayerController
	var world := game.get_node_or_null("ShipyardWorld") as ShipyardWorld
	var resolver := game.get_combat_resolver() as CombatResolver
	var hud := game.get_node_or_null("HUD") as CanvasLayer
	_check(
		player != null and world != null and resolver != null and hud != null,
		"the audit fixture exposes the production player, world, combat resolver and HUD"
	)
	if player == null or world == null or resolver == null or hud == null:
		await _tear_down(game)
		_finish()
		return

	await _wait_until(func() -> bool: return game.get_flyable_ships().size() >= 9, 4.0)
	var fleet: Array[HeroShip] = game.get_flyable_ships()
	_check(fleet.size() == 9, "the audit sees all nine production flyable craft")
	if fleet.size() != 9:
		await _tear_down(game)
		_finish()
		return

	var liveaboard := _find_liveaboard_craft(fleet)
	_check(
		liveaboard != null and liveaboard.supports_in_flight_cabin_access(),
		"the audit finds the liveaboard craft that publishes a walkable cabin and a bunk"
	)

	game.canopy_motion_time = 0.04
	game.boarding_motion_time = 0.08
	game.disembarking_motion_time = 0.06
	game.start_shift()
	await process_frame
	game.set("_guided_return_ready_for_completion", false)
	game.set("_guided_activity_complete", true)
	game.phase = GameFlow.Phase.COMPLETE
	_check(game.is_guided_activity_complete(), "the audit runs in the completed-guide sandbox")

	for cycle in _phantom_cycles:
		await _run_phantom_cycle(
			game, player, world, fleet, liveaboard, filesystem, cycle
		)

	_check(
		_cabin_bunk_round_trips == _phantom_cycles,
		"every cycle completed an in-flight cabin and bunk round trip (%d/%d)"
			% [_cabin_bunk_round_trips, _phantom_cycles]
	)
	_check(
		_destroyed_and_regenerated == _phantom_cycles,
		"every cycle destroyed and regenerated a parked craft (%d/%d)"
			% [_destroyed_and_regenerated, _phantom_cycles]
	)
	_check(
		_phantom_reentries == _phantom_cycles,
		"every cycle streamed the whole Main subtree out and back (%d/%d)"
			% [_phantom_reentries, _phantom_cycles]
	)
	_check(
		_states_snapshotted == _phantom_cycles * REST_STATES.size(),
		"every rest state was snapshotted in every cycle (%d/%d)"
			% [_states_snapshotted, _phantom_cycles * REST_STATES.size()]
	)

	await _tear_down(game)
	_print_phantom_summary()
	_finish()


# ----------------------------------------------------------------- cycle ----


func _run_phantom_cycle(
		game: GameFlow,
		player: PlayerController,
		world: ShipyardWorld,
		fleet: Array[HeroShip],
		liveaboard: HeroShip,
		filesystem: MemoryFilesystem,
		cycle: int
	) -> void:
	await _await_free_on_foot(game, player)
	await _snapshot_rest_state(world, player, cycle, STATE_ON_FOOT_YARD, "", null)

	var before_activity := _begin_leak_watch()
	if not await _start_and_abandon_nearby_activity(game, player, world):
		_check(false, "cycle %d starts and abandons one nearby-sector activity" % [cycle + 1])
	await _await_free_on_foot(game, player)
	player.teleport_to(world.get_player_spawn())
	await _end_leak_watch("starting and abandoning a nearby-sector activity", before_activity, cycle)
	await _snapshot_rest_state(world, player, cycle, STATE_ACTIVITY_ABANDONED, "", null)

	# The sortie is flown on the liveaboard craft every cycle: it is the only
	# production craft that publishes both a walkable cabin and a physical bunk,
	# and the nine-craft rotation is already owned by the long-session soak. The
	# destruction leg below still rotates across the whole fleet.
	var before_sortie := _begin_leak_watch()
	# Alternate how the sortie ends. `craft_parked` means the same thing either
	# way — the craft is at its berth and the pilot is on foot at the yard — so
	# two cycles that reach it by a normal landing and by losing the craft in
	# open space have to draw the same frame. The lost-in-flight half is the
	# deliverable's own example: a presentation stranded at the position a craft
	# was destroyed at has no craft left to be carried by.
	var flew := await _fly_cabin_bunk_sortie(
		game, player, world, liveaboard, cycle, cycle % 2 == 1
	)
	if not flew:
		await _recover_to_on_foot(game, player, world)
	await _await_free_on_foot(game, player)
	player.teleport_to(world.get_player_spawn())
	await _end_leak_watch("a whole sortie with a cabin and bunk round trip", before_sortie, cycle)
	await _snapshot_rest_state(
		world, player, cycle, STATE_CRAFT_PARKED, str(liveaboard.get_ship_id()), null
	)

	var doomed := fleet[cycle % fleet.size()]
	var before_destruction := _begin_leak_watch()
	await _damage_destroy_and_regenerate(doomed, cycle)
	await _await_free_on_foot(game, player)
	player.teleport_to(world.get_player_spawn())
	await _end_leak_watch(
		"destroying and regenerating %s" % doomed.get_ship_id(), before_destruction, cycle
	)
	await _snapshot_rest_state(
		world, player, cycle, STATE_DESTROYED_REGENERATED,
		str(doomed.get_ship_id()), null
	)

	var before_reentry := _begin_leak_watch()
	await _save_and_reenter(game, filesystem)
	_phantom_reentries += 1
	await _await_free_on_foot(game, player)
	player.teleport_to(world.get_player_spawn())
	await _end_leak_watch("a whole-Main save and re-entry", before_reentry, cycle)
	await _snapshot_rest_state(world, player, cycle, STATE_AFTER_REENTRY, "", null)


## The whole sortie for one cycle: board, launch, fire, leave the pilot seat into
## the cabin, sleep in a bunk, wake, retake the seat, and then either land
## through the real landing assist and disembark, or lose the craft in open space
## and let the berth regenerate it. The `cabin_bunk_returned` rest snapshot is
## taken in the seat with the craft holding station on its own berth's published
## capture pose, which is where anything the cabin or the bunk left behind would
## still be drawn.
func _fly_cabin_bunk_sortie(
		game: GameFlow,
		player: PlayerController,
		world: ShipyardWorld,
		craft: HeroShip,
		cycle: int,
		destroy_in_flight: bool
	) -> bool:
	if not await _walk_and_board(game, player, craft):
		_check(false, "cycle %d boards %s for the cabin sortie" % [cycle + 1, craft.get_ship_id()])
		return false
	await _wake_engine(craft)
	var launched := await _launch_and_fly(game, craft)
	_check(launched, "cycle %d launches %s into free flight" % [cycle + 1, craft.get_ship_id()])
	if not launched:
		return false

	await _fire_once(game, craft)

	var cabin_done := await _cabin_and_bunk_round_trip(game, player, craft, cycle)
	if cabin_done:
		_cabin_bunk_round_trips += 1
	await _snapshot_rest_state(
		world, player, cycle, STATE_CABIN_BUNK_RETURNED,
		str(craft.get_ship_id()), craft
	)
	if not cabin_done:
		return false

	if destroy_in_flight:
		return await _lose_craft_in_flight(player, world, craft, cycle)

	if not await _return_and_land(game, world, craft):
		_check(
			false,
			"cycle %d returns %s to its berth" % [cycle + 1, craft.get_ship_id()]
		)
		return false
	_check(
		await _disembark(game, player, craft),
		"cycle %d disembarks from %s at its berth" % [cycle + 1, craft.get_ship_id()]
	)
	return true


## Destroy the craft the player is flying, out in its own approach lane, and let
## the production regeneration recall put the pilot back on the station while the
## berth rebuilds the craft. Then look for anything still drawn at the position
## the craft was lost at.
func _lose_craft_in_flight(
		player: PlayerController,
		world: ShipyardWorld,
		craft: HeroShip,
		cycle: int
	) -> bool:
	var site := craft.global_position
	_death_sites.append(site)
	craft.apply_damage(craft.maximum_hull + 1.0, craft.global_position, Vector3.UP)
	for _destroy_tick in 6:
		await physics_frame
		await process_frame
	var recalled := await _wait_until(
		func() -> bool: return (
			not player.is_seated() and player.is_control_enabled()
			and not craft.is_destroyed() and craft.is_boardable()
		),
		10.0
	)
	_check(
		recalled,
		"cycle %d loses %s in flight and recalls the pilot to the station"
			% [cycle + 1, craft.get_ship_id()]
	)
	var lifetime_frames := int(ceil(
		(HeroDamagePresentation.DEBRIS_AFTERGLOW_LIFETIME + 6.0)
		* float(Engine.physics_ticks_per_second)
	))
	for _settle_tick in lifetime_frames:
		await physics_frame
		await process_frame
	var berth := world.get_berth_node(craft.get_home_berth_id())
	_check(
		is_instance_valid(berth)
		and craft.global_position.distance_to(berth.get_dock_transform().origin) < 12.0,
		"cycle %d regenerates %s back into its own berth" % [cycle + 1, craft.get_ship_id()]
	)
	var stranded := _transient_renderers_near(site, DEATH_SITE_RADIUS)
	_phantom_check(
		stranded.is_empty(),
		"cycle %d leaves nothing drawn where %s was destroyed at %s (%s)"
			% [cycle + 1, craft.get_ship_id(), site, ", ".join(_clip(stranded))]
	)
	return recalled


## Drawn transient renderers that are not carried by any craft and lie within
## `radius` of `site`. A destruction presentation is detached into the scene-tree
## root by design, so a stranded one has no ship ancestor to move it on.
func _transient_renderers_near(site: Vector3, radius: float) -> Array[String]:
	var walk := _walk_renderers()
	var near: Array[String] = []
	for path in walk.transient as Array[String]:
		var node := root.get_node_or_null(NodePath(path)) as Node3D
		if not is_instance_valid(node):
			continue
		if node.global_position.distance_to(site) <= radius:
			near.append(path)
	near.sort()
	return near


## Leave the pilot seat in open space, use a physical bunk, and come back. Every
## transition is the production one; only the two traverses of the aisle are
## staged, because this suite measures what is drawn at the far end of the
## lifecycle and `ship_sleep_gameplay_test` already owns the walk itself.
func _cabin_and_bunk_round_trip(
		game: GameFlow,
		player: PlayerController,
		craft: HeroShip,
		cycle: int
	) -> bool:
	_release_flight_controls(craft)
	craft.velocity = Vector3.ZERO
	var idle_frames := int(ceil(
		(HeroShip.AUTOMATIC_ENGINE_IDLE_SHUTDOWN_SECONDS + 0.2)
		* float(Engine.physics_ticks_per_second)
	))
	for _idle_tick in idle_frames:
		craft.velocity = Vector3.ZERO
		await physics_frame
		await process_frame
	if StringName(craft.get_telemetry().get("engine_state", &"")) != HeroShip.ENGINE_OFFLINE:
		_check(false, "cycle %d idles %s offline before cabin access" % [cycle + 1, craft.get_ship_id()])
		return false

	_dispatch_pilot_action(game, &"interact")
	var in_cabin := await _wait_until(
		func() -> bool: return (
			game.phase == GameFlow.Phase.IN_FLIGHT_CABIN
			and not player.is_seated()
			and player.is_control_enabled()
			and not bool(game.get("_transition_busy"))
		),
		3.0
	)
	_check(in_cabin, "cycle %d leaves the pilot seat into the in-flight cabin" % [cycle + 1])
	if not in_cabin:
		return false

	var bunk := _find_bunk(craft)
	if bunk == null:
		_check(false, "cycle %d finds a physical bunk aboard %s" % [cycle + 1, craft.get_ship_id()])
		return false
	var slept := await _use_bunk(game, player, craft, bunk)
	_check(slept, "cycle %d sleeps in and wakes from a physical bunk" % [cycle + 1])

	var reseated := await _retake_pilot_seat(game, player, craft)
	_check(reseated, "cycle %d retakes the pilot seat from the cabin" % [cycle + 1])
	return slept and reseated


func _use_bunk(
		game: GameFlow,
		player: PlayerController,
		craft: HeroShip,
		bunk: Node3D
	) -> bool:
	# The berth's discovery point sits directly above its own standing pose, so
	# a pilot standing exactly on that pose looks straight past it and the
	# production facing rule correctly refuses to offer the berth. Stage the
	# approach from the aisle instead, trying the craft's own local axes rather
	# than assuming which side of the hull this berth is on.
	var offered := false
	for offset in [
		craft.global_basis.z * 1.0, craft.global_basis.z * -1.0,
		craft.global_basis.x * 1.0, craft.global_basis.x * -1.0,
		craft.global_basis.z * 1.6, craft.global_basis.z * -1.6,
	]:
		var stand := bunk.global_position + (offset as Vector3) - craft.global_basis.y * 0.9
		var facing := -(offset as Vector3).normalized()
		player.teleport_to(Transform3D(Basis.looking_at(facing, craft.global_basis.y), stand))
		offered = await _wait_until(
			func() -> bool: return game.station_interaction_candidate == bunk,
			0.4
		)
		if offered:
			break
	if not offered:
		return false
	await _press_live_action(&"interact", 1)
	if not await _wait_until(func() -> bool: return player.is_sleeping(), 2.5):
		return false
	for _rest_tick in 30:
		await physics_frame
		await process_frame
	await _press_live_action(&"interact", 1)
	if not await _wait_until(
		func() -> bool: return not player.is_sleeping() and player.is_control_enabled(),
		2.5
	):
		return false
	for _wake_tick in 8:
		await physics_frame
		await process_frame
	return bool(bunk.call("is_available"))


func _retake_pilot_seat(game: GameFlow, player: PlayerController, craft: HeroShip) -> bool:
	var report := craft.get_in_flight_cabin_report()
	var stand := report.get("stand_transform", Transform3D.IDENTITY) as Transform3D
	player.teleport_to(stand)
	for _stage_tick in 8:
		await physics_frame
		await process_frame
	if game.boarding_candidate != craft:
		# Turn on the spot toward the craft's own forward axis; the seat's
		# boarding area is discovered by the same facing-weighted proximity rule
		# the production cabin uses, and the stand pose is already inside it.
		player.teleport_to(Transform3D(
			Basis.looking_at(-craft.global_basis.z, craft.global_basis.y),
			player.global_position
		))
		await _wait_until(func() -> bool: return game.boarding_candidate == craft, 1.0)
	if game.boarding_candidate != craft:
		return false
	await _press_live_action(&"interact", 1)
	return await _wait_until(
		func() -> bool: return (
			player.is_seated() and craft.is_piloted()
			and not bool(game.get("_transition_busy"))
		),
		3.0
	)


## Damage a parked craft to critical, confirm the audit can actually see its
## damage channels raised, then destroy it and let the berth regenerate it. A
## channel that never raises would make every later "no transient renderer at
## rest" pass meaningless.
func _damage_destroy_and_regenerate(craft: HeroShip, cycle: int) -> void:
	if craft.is_destroyed():
		await _wait_until(func() -> bool: return not craft.is_destroyed(), 6.0)
	craft.apply_damage(craft.maximum_hull * 0.8, craft.global_position, Vector3.UP)
	for _damage_tick in 12:
		await physics_frame
		await process_frame
	var raised := _transient_paths_under(craft)
	# The three runtime-composed Cinder craft carry no `HeroDamagePresentation`
	# at all (only the six craft with a `scenes/ships/*.tscn` instance one), so
	# there is no shared damage channel of theirs to raise. That gap is reported
	# in `docs/LIFECYCLE_PHANTOM_AUDIT.md`; it is a missing presentation, not a
	# phantom, and it belongs to the fleet presentation-coverage item.
	if craft.get_damage_presentation() != null:
		_check(
			not craft.is_destroyed() and not raised.is_empty(),
			"cycle %d raises %s's damage channels before destroying it (%s)"
				% [cycle + 1, craft.get_ship_id(), ", ".join(_clip(raised))]
		)
	else:
		_craft_without_damage_presentation_ids[str(craft.get_ship_id())] = true

	craft.apply_damage(craft.maximum_hull + 1.0, craft.global_position, Vector3.UP)
	for _destroy_tick in 6:
		await physics_frame
		await process_frame
	var destroyed := craft.is_destroyed()
	var recovered := await _wait_until(
		func() -> bool: return not craft.is_destroyed() and craft.is_boardable(),
		8.0
	)
	_check(
		destroyed and recovered,
		"cycle %d loses and regenerates %s at its berth" % [cycle + 1, craft.get_ship_id()]
	)
	if destroyed and recovered:
		_destroyed_and_regenerated += 1
	# The destruction presentation owns a bounded lifetime of its own; the rest
	# snapshot must be taken after it, not during it.
	var lifetime_frames := int(ceil(
		(HeroDamagePresentation.DEBRIS_AFTERGLOW_LIFETIME + 6.0)
		* float(Engine.physics_ticks_per_second)
	))
	for _settle_tick in lifetime_frames:
		await physics_frame
		await process_frame
	_check(
		_transient_paths_under(craft).is_empty(),
		"cycle %d clears every damage channel on the regenerated %s (%s)"
			% [cycle + 1, craft.get_ship_id(), ", ".join(_clip(_transient_paths_under(craft)))]
	)


## Drawn transient renderers inside one craft, by the same rule the rest
## snapshot uses.
func _transient_paths_under(craft: HeroShip) -> Array[String]:
	var walk := {
		"visible": {}, "lights": {}, "light_nodes": [] as Array[Node],
		"emitting": [] as Array[String], "transient": [] as Array[String],
		"particle_systems": 0,
	}
	_collect_renderers(craft, "", craft.global_transform.affine_inverse(), true, walk)
	var transient := walk.transient as Array[String]
	transient.sort()
	return transient


func _find_liveaboard_craft(fleet: Array[HeroShip]) -> HeroShip:
	for craft: HeroShip in fleet:
		if craft is HalyardTransport and _find_bunk(craft) != null:
			return craft
	for craft: HeroShip in fleet:
		if craft.supports_in_flight_cabin_access() and _find_bunk(craft) != null:
			return craft
	return null


func _find_bunk(craft: HeroShip) -> Node3D:
	for candidate in craft.find_children("*", "Area3D", true, false):
		if candidate is BunkInteraction:
			return candidate as Node3D
	return null


## Same-cycle leak watch. A cross-cycle diff cannot see a phantom that was
## already there in the previous cycle; a before/after pair bracketing one
## lifecycle can. Returns the visible renderer set to hand back to
## [method _end_leak_watch].
func _begin_leak_watch() -> Dictionary:
	return _walk_renderers().visible as Dictionary


func _end_leak_watch(label: String, before: Dictionary, cycle: int) -> void:
	for _settle_tick in REST_SETTLE_TICKS:
		await physics_frame
		await process_frame
	var after := _walk_renderers()
	var raw_gained := _path_difference(after.visible as Dictionary, before)
	var gained := _without_lod_alternates(raw_gained)
	var emitting := after.emitting as Array[String]
	_leak_watches += 1
	print("PHANTOM_LEAK %s" % JSON.stringify({
		"cycle": cycle + 1,
		"after": label,
		"gained": gained.size(),
		"gained_lod_alternates": raw_gained.size() - gained.size(),
		"emitting": emitting.size(),
		"gained_paths": _clip(gained),
	}))
	if cycle < PHANTOM_WARM_UP_CYCLES:
		return
	_phantom_check(
		gained.is_empty(),
		"cycle %d draws nothing new after %s (%s)"
			% [cycle + 1, label, ", ".join(_clip(gained))]
	)
	_phantom_check(
		emitting.is_empty(),
		"cycle %d leaves no particle system emitting after %s (%s)"
			% [cycle + 1, label, ", ".join(_clip(emitting))]
	)


# --------------------------------------------------------------- snapshot ----


## One rest state: stage a deterministic viewpoint, settle, snapshot the visible
## renderer set, sample every visible light for two simulated seconds, snapshot
## again, diff against the same state one cycle ago, assert, and print one
## `PHANTOM_CYCLE` line.
##
## The viewpoint is staged because several production craft swap LOD renderers
## by camera distance. Two cycles that photographed the yard from two different
## places would differ in which LOD batch is drawn, and a visible-set diff has to
## compare the same frame, not two legitimate frames.
func _snapshot_rest_state(
		world: ShipyardWorld,
		player: PlayerController,
		cycle: int,
		state_id: StringName,
		subject: String,
		held_craft: HeroShip
	) -> void:
	_release_all_actions()
	_held_craft = held_craft
	_held_craft_pose = Transform3D.IDENTITY
	if is_instance_valid(held_craft):
		var berth := world.get_berth_node(held_craft.get_home_berth_id())
		_held_craft_pose = (
			berth.get_assist_capture_transform()
			if is_instance_valid(berth) else held_craft.global_transform
		)
	elif not player.is_seated():
		player.teleport_to(world.get_player_spawn())
	_hold_rest_pose()
	for _settle_tick in REST_SETTLE_TICKS:
		await physics_frame
		await process_frame
		_hold_rest_pose()

	var opening := _walk_renderers()
	var series := await _sample_light_series(opening.light_nodes as Array[Node])
	var closing := _walk_renderers()
	_held_craft = null
	_states_snapshotted += 1

	var assertable := cycle >= PHANTOM_WARM_UP_CYCLES
	var record := {
		"cycle": cycle + 1,
		"state": str(state_id),
		"subject": subject,
		"asserted": assertable,
		"visible_renderers": (opening.visible as Dictionary).size(),
		"visible_lights": (opening.lights as Dictionary).size(),
		"particle_systems": int(opening.particle_systems),
		"emitting_particle_systems": (opening.emitting as Array[String]).size(),
		"transient_visible": (opening.transient as Array[String]).size(),
	}

	# --- flicker and animation across the rest window ------------------------
	var flicker := _path_difference(closing.visible as Dictionary, opening.visible as Dictionary)
	var extinguished := _path_difference(opening.visible as Dictionary, closing.visible as Dictionary)
	var animated := _moved_beyond(
		opening.visible as Dictionary, closing.visible as Dictionary, WINDOW_MOTION_EPSILON
	)
	record["appeared_during_window"] = flicker.size()
	record["vanished_during_window"] = extinguished.size()
	record["animated_during_window"] = animated.size()
	if not flicker.is_empty() or not extinguished.is_empty():
		record["window_flicker_paths"] = _clip(flicker + extinguished)

	# --- absolute contracts ---------------------------------------------------
	var emitting := opening.emitting as Array[String]
	var transient := opening.transient as Array[String]
	var flashers := series.flashing as Array[Dictionary]
	var unsafe_declared := series.unsafe_declared as Array[Dictionary]
	var over_contract := series.over_contract as Array[Dictionary]
	var lifecycle_flashing := series.lifecycle_flashing as Array[Dictionary]
	record["flashing_lights"] = flashers.size()
	record["lights_over_flash_contract"] = over_contract.size()
	record["lifecycle_lights_flashing"] = lifecycle_flashing.size()
	if not over_contract.is_empty() or not lifecycle_flashing.is_empty() \
			or not unsafe_declared.is_empty():
		record["flashing_light_series"] = (
			over_contract + lifecycle_flashing + unsafe_declared
		).slice(0, MAX_REPORTED_PATHS)
	if not emitting.is_empty():
		record["emitting_paths"] = _clip(emitting)
	if not transient.is_empty():
		record["transient_paths"] = _clip(transient)

	# --- berth lease displays -------------------------------------------------
	var lease := _audit_berth_lease_displays(world)
	record["berth_lease_displays"] = int(lease.audited)
	record["berth_lease_defects"] = (lease.defects as Array[String]).size()
	if not (lease.defects as Array[String]).is_empty():
		record["berth_lease_defect_paths"] = _clip(lease.defects as Array[String])

	# --- cycle-to-cycle diff of the same state -------------------------------
	var previous: Dictionary = _state_history.get(state_id, {}) as Dictionary
	var gained: Array[String] = []
	var lost: Array[String] = []
	var moved: Array[String] = []
	var relit: Array[String] = []
	var restated: Array[String] = []
	if not previous.is_empty():
		var previous_visible := previous.get("visible", {}) as Dictionary
		var raw_gained := _path_difference(opening.visible as Dictionary, previous_visible)
		gained = _without_lod_alternates(raw_gained)
		lost = _without_lod_alternates(
			_path_difference(previous_visible, opening.visible as Dictionary)
		)
		record["gained_lod_alternates"] = raw_gained.size() - gained.size()
		# Only renderers that held still inside both rest windows are held to a
		# position between cycles; an authored animation has no resting pose to
		# be compared against.
		var excluded := _union(animated, previous.get("animated", [] as Array[String]) as Array[String])
		moved = _moved_renderers(previous_visible, opening.visible as Dictionary, excluded)
		restated = _changed_labels(previous_visible, opening.visible as Dictionary)
		record["restated_displays"] = restated.size()
		if not restated.is_empty():
			record["restated_display_paths"] = _clip(restated)
		relit = _changed_lights(
			previous.get("lights", {}) as Dictionary,
			opening.lights as Dictionary,
			_union(
				_flashing_paths(flashers),
				previous.get("flashing_lights", [] as Array[String]) as Array[String]
			)
		)
		record["gained_visible"] = gained.size()
		record["lost_visible"] = lost.size()
		record["moved_renderers"] = moved.size()
		record["changed_lights"] = relit.size()
		if not gained.is_empty():
			record["gained_paths"] = _clip(gained)
		if not lost.is_empty():
			record["lost_paths"] = _clip(lost)
		if not moved.is_empty():
			record["moved_paths"] = _clip(moved)
		if not relit.is_empty():
			record["changed_light_paths"] = _clip(relit)

	if assertable:
		_phantom_check(
			transient.is_empty(),
			"%s cycle %d draws no transient damage/destruction/repair renderer at rest (%s)"
				% [state_id, cycle + 1, ", ".join(_clip(transient))]
		)
		_phantom_check(
			emitting.is_empty(),
			"%s cycle %d has no particle system emitting at rest (%s)"
				% [state_id, cycle + 1, ", ".join(_clip(emitting))]
		)
		_phantom_check(
			over_contract.is_empty(),
			"%s cycle %d keeps every visible light inside the reduced-flash contract (%s)"
				% [state_id, cycle + 1, _describe_flashers(over_contract)]
		)
		_phantom_check(
			lifecycle_flashing.is_empty(),
			"%s cycle %d holds every lifecycle presentation light steady at rest (%s)"
				% [state_id, cycle + 1, _describe_flashers(lifecycle_flashing)]
		)
		_phantom_check(
			unsafe_declared.is_empty(),
			"%s cycle %d keeps every reduced_flash_safe light unmodulated (%s)"
				% [state_id, cycle + 1, _describe_flashers(unsafe_declared)]
		)
		_phantom_check(
			flicker.is_empty() and extinguished.is_empty(),
			"%s cycle %d draws the same renderer set for the whole rest window (%s)"
				% [state_id, cycle + 1, ", ".join(_clip(flicker + extinguished))]
		)
		_phantom_check(
			(lease.defects as Array[String]).is_empty(),
			"%s cycle %d shows one lease display state per berth (%s)"
				% [state_id, cycle + 1, ", ".join(_clip(lease.defects as Array[String]))]
		)
		if not previous.is_empty():
			_phantom_check(
				gained.is_empty(),
				"%s cycle %d gains no visible renderer over the previous cycle (%s)"
					% [state_id, cycle + 1, ", ".join(_clip(gained))]
			)
			_phantom_check(
				moved.is_empty(),
				"%s cycle %d leaves no resting renderer at a stale position (%s)"
					% [state_id, cycle + 1, ", ".join(_clip(moved))]
			)
			_phantom_check(
				relit.is_empty(),
				"%s cycle %d re-lights no steady light between cycles (%s)"
					% [state_id, cycle + 1, ", ".join(_clip(relit))]
			)
			_phantom_check(
				restated.is_empty(),
				"%s cycle %d shows the same text on every world display (%s)"
					% [state_id, cycle + 1, " | ".join(_clip(restated))]
			)

	_state_history[state_id] = {
		"visible": opening.visible,
		"lights": opening.lights,
		"animated": animated,
		"flashing_lights": _flashing_paths(flashers),
	}
	_state_records.append(record)
	print("PHANTOM_CYCLE %s" % JSON.stringify(record))


## Holds the staged rest pose. A craft the audit parks in its own berth's
## published capture pose must still be there two simulated seconds later, or the
## snapshot would be of a drifting frame.
func _hold_rest_pose() -> void:
	if not is_instance_valid(_held_craft):
		return
	_held_craft.global_transform = _held_craft_pose
	_held_craft.velocity = Vector3.ZERO


## One walk of the live tree from the scene-tree root. Destruction effects are
## detached into the root by `HeroDamagePresentation._get_world_effect_host()`,
## so the walk deliberately does not start at `Main`.
func _walk_renderers() -> Dictionary:
	var result := {
		"visible": {},
		"lights": {},
		"light_nodes": [] as Array[Node],
		"emitting": [] as Array[String],
		"transient": [] as Array[String],
		"particle_systems": 0,
	}
	_collect_renderers(root, "", Transform3D.IDENTITY, false, result)
	(result.emitting as Array[String]).sort()
	(result.transient as Array[String]).sort()
	return result


func _collect_renderers(
		node: Node,
		parent_path: String,
		ship_inverse: Transform3D,
		inside_ship: bool,
		result: Dictionary
	) -> void:
	var path := parent_path + "/" + String(node.name)
	var node_inverse := ship_inverse
	var node_inside_ship := inside_ship
	if node is HeroShip:
		node_inverse = (node as HeroShip).global_transform.affine_inverse()
		node_inside_ship = true

	if node is GPUParticles3D or node is CPUParticles3D \
			or node is GPUParticles2D or node is CPUParticles2D:
		result["particle_systems"] = int(result.particle_systems) + 1
		if bool(node.get(&"emitting")):
			(result.emitting as Array[String]).append(path)

	if node is GeometryInstance3D:
		var geometry := node as GeometryInstance3D
		if geometry.is_visible_in_tree():
			var box := geometry.get_aabb()
			var reference := (
				node_inverse * geometry.global_transform
				if node_inside_ship
				else geometry.global_transform
			)
			var emitting_variant: Variant = null
			if geometry is GPUParticles3D or geometry is CPUParticles3D:
				emitting_variant = bool(geometry.get(&"emitting"))
			(result.visible as Dictionary)[path] = {
				"cls": geometry.get_class(),
				"aabb": _encode_aabb(reference, box),
				"shadow": int(geometry.cast_shadow),
				"transparency": snappedf(geometry.transparency, 0.001),
				"emitting": emitting_variant,
				# A `Label3D`'s AABB is a function of the string it is showing,
				# so the string is the readable form of "this display moved".
				"text": String(geometry.get(&"text")) if geometry is Label3D else "",
			}
			if geometry.transparency < DRAWN_TRANSPARENCY_LIMIT \
					and _matches_any(String(node.name), TRANSIENT_RENDERER_NAMES):
				(result.transient as Array[String]).append(path)
	elif node is Light3D:
		var light := node as Light3D
		if light.is_visible_in_tree():
			(result.lights as Dictionary)[path] = {
				"cls": light.get_class(),
				"energy": snappedf(light.light_energy, 0.0001),
				"reduced_flash_safe": bool(light.get_meta(&"reduced_flash_safe", false)),
			}
			(result.light_nodes as Array[Node]).append(light)
			# A production damage cue parks its light in the tree at zero energy
			# between lifecycles rather than hiding it, so energy is what decides
			# whether the cue is on screen.
			if light.light_energy > REST_LIGHT_ENERGY_EPSILON \
					and _matches_any(String(node.name), TRANSIENT_LIGHT_NAMES):
				(result.transient as Array[String]).append(path)

	for child in node.get_children():
		_collect_renderers(child, path, node_inverse, node_inside_ship, result)


## Per-tick light energy over `LIGHT_SERIES_SECONDS` of simulated time. Only the
## extremes, the turning-point count and the endpoints are retained: a series is
## a flash if its amplitude is non-zero, and its period follows from how many
## times it turned around inside a known window.
func _sample_light_series(lights: Array[Node]) -> Dictionary:
	var ticks := maxi(
		2, int(round(LIGHT_SERIES_SECONDS * float(Engine.physics_ticks_per_second)))
	)
	var minimums := PackedFloat32Array()
	var maximums := PackedFloat32Array()
	var previous := PackedFloat32Array()
	var direction := PackedInt32Array()
	var turns := PackedInt32Array()
	minimums.resize(lights.size())
	maximums.resize(lights.size())
	previous.resize(lights.size())
	direction.resize(lights.size())
	turns.resize(lights.size())
	for index in lights.size():
		var energy := float((lights[index] as Light3D).light_energy)
		minimums[index] = energy
		maximums[index] = energy
		previous[index] = energy
		direction[index] = 0
		turns[index] = 0

	for _tick in ticks:
		await physics_frame
		await process_frame
		_hold_rest_pose()
		for index in lights.size():
			var light := lights[index] as Light3D
			if not is_instance_valid(light):
				continue
			var energy := float(light.light_energy)
			minimums[index] = minf(minimums[index], energy)
			maximums[index] = maxf(maximums[index], energy)
			var delta := energy - previous[index]
			if absf(delta) > REST_LIGHT_ENERGY_EPSILON:
				var sign_value := 1 if delta > 0.0 else -1
				if direction[index] != 0 and sign_value != direction[index]:
					turns[index] = turns[index] + 1
				direction[index] = sign_value
			previous[index] = energy

	var flashing: Array[Dictionary] = []
	var unsafe_declared: Array[Dictionary] = []
	var over_contract: Array[Dictionary] = []
	var lifecycle_flashing: Array[Dictionary] = []
	for index in lights.size():
		var light := lights[index] as Light3D
		if not is_instance_valid(light):
			continue
		var amplitude := maximums[index] - minimums[index]
		if amplitude <= REST_LIGHT_ENERGY_EPSILON:
			continue
		var descriptor := {
			"path": String(light.get_path()),
			"amplitude": snappedf(amplitude, 0.0001),
			"minimum": snappedf(minimums[index], 0.0001),
			"maximum": snappedf(maximums[index], 0.0001),
			"depth": snappedf(
				amplitude / maxf(maximums[index], REST_LIGHT_ENERGY_EPSILON), 0.001
			),
			"turning_points": turns[index],
			# Two turning points make one full period, so the window holds
			# `turns / 2` periods.
			"period_seconds": (
				snappedf(LIGHT_SERIES_SECONDS / (float(turns[index]) * 0.5), 0.001)
				if turns[index] > 0 else 0.0
			),
			"flash_hz": (
				snappedf(float(turns[index]) * 0.5 / LIGHT_SERIES_SECONDS, 0.01)
				if turns[index] > 0 else 0.0
			),
			"reduced_flash_safe": bool(light.get_meta(&"reduced_flash_safe", false)),
		}
		flashing.append(descriptor)
		if bool(descriptor.reduced_flash_safe):
			unsafe_declared.append(descriptor)
		if float(descriptor.flash_hz) > MAX_REST_FLASH_HZ \
				or float(descriptor.depth) > MAX_REST_FLASH_DEPTH:
			over_contract.append(descriptor)
		if _matches_any(String(descriptor.path), LIFECYCLE_PATH_MARKERS):
			lifecycle_flashing.append(descriptor)
	return {
		"flashing": flashing,
		"unsafe_declared": unsafe_declared,
		"over_contract": over_contract,
		"lifecycle_flashing": lifecycle_flashing,
	}


## Exactly one lease-state glyph is ever meant to be rendered per berth, and the
## approach guides only in the approach state. A berth whose craft was replaced
## leaving two glyph states lit at once is the display half of a phantom.
func _audit_berth_lease_displays(world: ShipyardWorld) -> Dictionary:
	var defects: Array[String] = []
	var audited := 0
	for node in world.find_children("*", "ShipBerthFeedback", true, false):
		var feedback := node as ShipBerthFeedback
		if not is_instance_valid(feedback) or not feedback.is_visible_in_tree():
			continue
		audited += 1
		var snapshot := feedback.get_state_snapshot()
		var expected := PackedStringArray(snapshot.get("cue_glyph_mesh_names", PackedStringArray()))
		var drawn := PackedStringArray()
		for child in feedback.find_children("Glyph*", "MeshInstance3D", true, false):
			var glyph := child as MeshInstance3D
			if is_instance_valid(glyph) and glyph.is_visible_in_tree():
				drawn.append(String(glyph.name))
		drawn.sort()
		if drawn != expected:
			defects.append("%s:drawn[%s]!=state[%s]" % [
				String(feedback.name), ", ".join(drawn), ", ".join(expected)
			])
		var approach := StringName(snapshot.get("state", &"")) == ShipBerthFeedback.STATE_APPROACH
		for child in feedback.find_children("ApproachGuide*", "MeshInstance3D", true, false):
			var guide := child as MeshInstance3D
			if is_instance_valid(guide) and guide.is_visible_in_tree() and not approach:
				defects.append("%s:%s lit outside approach" % [String(feedback.name), String(guide.name)])
	defects.sort()
	return {"audited": audited, "defects": defects}


# ------------------------------------------------------------------ diff ----


func _encode_aabb(reference: Transform3D, box: AABB) -> PackedFloat32Array:
	var transformed := reference * box
	return PackedFloat32Array([
		snappedf(transformed.position.x, 0.001),
		snappedf(transformed.position.y, 0.001),
		snappedf(transformed.position.z, 0.001),
		snappedf(transformed.size.x, 0.001),
		snappedf(transformed.size.y, 0.001),
		snappedf(transformed.size.z, 0.001),
	])


func _path_difference(left: Dictionary, right: Dictionary) -> Array[String]:
	var only: Array[String] = []
	for path_variant: Variant in left.keys():
		if not right.has(path_variant):
			only.append(str(path_variant))
	only.sort()
	return only


## Paths whose AABB differs between two renderer snapshots by more than
## `tolerance`, ignoring any path in `excluded`.
func _moved_beyond(
		previous: Dictionary,
		current: Dictionary,
		tolerance: float,
		excluded: Array[String] = [] as Array[String]
	) -> Array[String]:
	var moved: Array[String] = []
	for path_variant: Variant in current.keys():
		if not previous.has(path_variant) or excluded.has(str(path_variant)):
			continue
		if str((current[path_variant] as Dictionary).get("cls", "")) == "Label3D":
			# A world display's AABB tracks the string it is showing. Its text is
			# audited directly by `_changed_labels`, which says what changed.
			continue
		var before := (previous[path_variant] as Dictionary).get("aabb", PackedFloat32Array()) as PackedFloat32Array
		var after := (current[path_variant] as Dictionary).get("aabb", PackedFloat32Array()) as PackedFloat32Array
		if before.size() != after.size():
			moved.append(str(path_variant))
			continue
		var drift := 0.0
		for index in before.size():
			drift = maxf(drift, absf(after[index] - before[index]))
		if drift > tolerance:
			moved.append(str(path_variant) if tolerance <= WINDOW_MOTION_EPSILON \
				else "%s(+%.2fm)" % [str(path_variant), drift])
	moved.sort()
	return moved


func _moved_renderers(
		previous: Dictionary, current: Dictionary, excluded: Array[String]
	) -> Array[String]:
	return _moved_beyond(previous, current, AABB_DRIFT_TOLERANCE, excluded)


func _changed_lights(
		previous: Dictionary, current: Dictionary, excluded: Array[String]
	) -> Array[String]:
	var changed: Array[String] = []
	for path_variant: Variant in current.keys():
		if excluded.has(str(path_variant)):
			continue
		if not previous.has(path_variant):
			changed.append("%s(new)" % str(path_variant))
			continue
		var before := float((previous[path_variant] as Dictionary).get("energy", 0.0))
		var after := float((current[path_variant] as Dictionary).get("energy", 0.0))
		if absf(after - before) > REST_LIGHT_ENERGY_EPSILON:
			changed.append("%s(%.3f->%.3f)" % [str(path_variant), before, after])
	changed.sort()
	return changed


func _without_lod_alternates(paths: Array[String]) -> Array[String]:
	var kept: Array[String] = []
	for path in paths:
		if not _matches_any(path, LOD_ALTERNATE_MARKERS):
			kept.append(path)
	return kept


## World displays whose text differs between two visits to the same rest state.
## A berth whose craft was replaced, or a cabin panel whose craft was lost and
## rebuilt, has to come back reading what it read the last time the player stood
## in the same place.
func _changed_labels(previous: Dictionary, current: Dictionary) -> Array[String]:
	var restated: Array[String] = []
	for path_variant: Variant in current.keys():
		if not previous.has(path_variant):
			continue
		var entry := current[path_variant] as Dictionary
		if str(entry.get("cls", "")) != "Label3D":
			continue
		var after := str(entry.get("text", ""))
		var before := str((previous[path_variant] as Dictionary).get("text", ""))
		if after != before:
			restated.append("%s: %s => %s" % [
				str(path_variant),
				before.replace("\n", " / "),
				after.replace("\n", " / "),
			])
	restated.sort()
	return restated


func _flashing_paths(flashers: Array[Dictionary]) -> Array[String]:
	var paths: Array[String] = []
	for descriptor in flashers:
		paths.append(str(descriptor.get("path", "")))
	return paths


func _union(left: Array[String], right: Array[String]) -> Array[String]:
	var merged: Array[String] = left.duplicate()
	for value in right:
		if not merged.has(value):
			merged.append(value)
	return merged


func _matches_any(name_text: String, patterns: Array[String]) -> bool:
	for pattern in patterns:
		if name_text.contains(pattern):
			return true
	return false


func _clip(paths: Array[String]) -> Array[String]:
	if paths.size() <= MAX_REPORTED_PATHS:
		return paths
	var clipped := paths.slice(0, MAX_REPORTED_PATHS)
	clipped.append("... +%d more" % (paths.size() - MAX_REPORTED_PATHS))
	return clipped


func _describe_flashers(flashers: Array[Dictionary]) -> String:
	var parts: Array[String] = []
	for descriptor in flashers.slice(0, MAX_REPORTED_PATHS):
		parts.append("%s amplitude %.3f depth %.2f at %.2f Hz" % [
			str(descriptor.get("path", "")),
			float(descriptor.get("amplitude", 0.0)),
			float(descriptor.get("depth", 0.0)),
			float(descriptor.get("flash_hz", 0.0)),
		])
	return "; ".join(parts)


func _phantom_check(condition: bool, description: String) -> void:
	if not condition:
		_phantom_failures += 1
	_check(condition, description)


func _print_phantom_summary() -> void:
	var summary := {
		"schema_version": 1,
		"cycles": _phantom_cycles,
		"warm_up_cycles": PHANTOM_WARM_UP_CYCLES,
		"rest_states": REST_STATES.size(),
		"states_snapshotted": _states_snapshotted,
		"cabin_bunk_round_trips": _cabin_bunk_round_trips,
		"destroyed_and_regenerated": _destroyed_and_regenerated,
		"reentries": _phantom_reentries,
		"light_series_seconds": LIGHT_SERIES_SECONDS,
		"aabb_drift_tolerance_m": AABB_DRIFT_TOLERANCE,
		"leak_watches": _leak_watches,
		"in_flight_losses": _death_sites.size(),
		"death_site_radius_m": DEATH_SITE_RADIUS,
		"craft_without_damage_presentation": _craft_without_damage_presentation_ids.keys(),
		"phantom_failures": _phantom_failures,
		"assertions": _assertions,
		"failures": _failures.size(),
		"states": _state_records,
	}
	print("PHANTOM_SUMMARY %s" % JSON.stringify(summary))


func _finish() -> void:
	if _failures.is_empty():
		print("LIFECYCLE_PHANTOM_GEOMETRY_TEST_OK: %d assertions" % _assertions)
		quit(0)
	else:
		printerr(
			"LIFECYCLE_PHANTOM_GEOMETRY_TEST_FAILED: %d/%d assertions failed: %s"
			% [_failures.size(), _assertions, "; ".join(_failures)]
		)
		quit(1)
