class_name CreditsCatalog
extends RefCounted

## Player-facing credits and attribution content for the CREDITS page.
##
## ASSETS.md is a repository document and is not exported with the game, so its
## register is transcribed here: one entry per ASSETS.md heading, in the same
## order, carrying the authorship and licence status that register records.
## tests/credits_page_test.gd parses ASSETS.md and fails if a heading is added
## there without a matching entry here. Nothing in this file invents a person:
## the repository records no individual contributor names, so the team is
## credited as the "Mudds Shipyards team".

const GAME_TITLE := "MUDDS SHIPYARDS"
const TEAM_NAME := "Mudds Shipyards team"
const REPOSITORY := "github.com/themuddfamily/mudds-shipyards"

const PROJECT_ORIGINAL := "Project-original work for Mudds Shipyards. No third-party material; no third-party licence applies."
const IMAGEGEN_ORIGINAL := "Project-original output of OpenAI's built-in image generation tool. Not sourced from Roblox, the original Keth Shipyards or third-party artwork."

## Transcribed from ASSETS.md. `register` is the heading exactly as it appears
## there with Markdown backticks removed.
const ASSET_ENTRIES: Array[Dictionary] = [
	{
		"register": "assets/signage/station_wayfinding_atlas.svg — station wayfinding sign atlas",
		"kind": "Textures",
		"credit": "Twenty-nine destination plates, shape cues and arrows generated by tools/signage/generate_station_wayfinding_atlas.py with the project's font-free engineering alphabet. Original modern interpretation; no external fonts or images.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Original fleet registration and safety markings",
		"kind": "Textures",
		"credit": "Twenty-two SVG registration, safety and freight markings generated by tools/generate_ship_markings.py. All lettering is explicit vector paths; no external fonts or images.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Manufactured fleet paint",
		"kind": "Textures",
		"credit": "Seamless paint albedo, normal, roughness and packed ORM channels generated by tools/generate_ship_finish_maps.py and tools/generate_station_orm_map.py.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Zenith B7 evidence and project-original runtime assets",
		"kind": "Models",
		"credit": "A public video rendition was inspected as research and is referenced by metadata and hash only. No source video, frame or screenshot is bundled or shipped.",
		"licence": "Runtime Zenith assets are project-original. Redistribution rights for the inspected research source are not recorded, so it is not included.",
	},
	{
		"register": "art_source/zenith/zenith_authored_v1.blend",
		"kind": "Models",
		"credit": "Editable Zenith source built by tools/blender/generate_zenith_authored_v1.py under Blender 4.0.2.",
		"licence": "Original script-assisted Blender work. No source pixels, source meshes, Roblox assets or third-party geometry.",
	},
	{
		"register": "assets/models/zenith/zenith_authored_art.glb",
		"kind": "Models",
		"credit": "Presentation-only Zenith art exported from the project Blender source.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "assets/models/zenith/zenith_authored_asset_manifest.json",
		"kind": "Models",
		"credit": "Machine-readable authorship and evidence-scope record for the authored Zenith.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Zenith definition and runtime wrappers",
		"kind": "Models",
		"credit": "Zenith ship definition, scene and runtime scripts; collision, flight and systems are modern project work.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "art_source/station/central_berth_hero_v1.blend",
		"kind": "Models",
		"credit": "Central Torrent berth shell built by tools/blender/generate_central_berth_hero_v1.py under Blender 4.0.2.",
		"licence": "Original script-assisted Blender work; not recovered Roblox geometry.",
	},
	{
		"register": "assets/effects/mudds-combat-vfx-atlas-v1.png",
		"kind": "Effects",
		"credit": "Tintable pulse, impact, explosion and shock-ring sprite atlas.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/concepts/torrent/torrent-hero-concept-multiview-v1.png",
		"kind": "Concept art",
		"credit": "Four-view Torrent visual-development reference; a design target only.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/models/torrent/textures/torrent-hero-trim-albedo-v1.png",
		"kind": "Textures",
		"credit": "Torrent hero UV trim atlas source.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/models/torrent/textures/torrent-hero-flat-albedo-study-v1.png",
		"kind": "Textures",
		"credit": "Flatter Torrent hull material study edited from the trim source.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "Torrent hero runtime texture derivatives",
		"kind": "Textures",
		"credit": "Runtime-size albedo, normal, roughness, ORM and emissive maps derived by tools/generate_material_maps.gd.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Symmetric station triplanar PBR set",
		"kind": "Textures",
		"credit": "Station panel albedo, normal and roughness set from a fixed-recipe procedural generator (tools/generate_material_maps.gd).",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "assets/materials/cockpit-anti-glare-composite-v1.png",
		"kind": "Textures",
		"credit": "Woven-composite albedo for the Torrent's anti-glare instrument hood.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/materials/jovian-hull-albedo-v1.png",
		"kind": "Textures",
		"credit": "Pearl-grey cargo-spacecraft panel albedo for the Jovian light freighter.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/materials/shipyard-deck-albedo-v1.png",
		"kind": "Textures",
		"credit": "Blue-grey operational deck and structural-cladding albedo.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "Registered derived material maps",
		"kind": "Textures",
		"credit": "Normal and roughness maps derived from the Torrent, Arrow, Jovian and deck albedos by tools/generate_material_maps.gd.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Fleet structural surface treatment (runtime rebinding, no new bytes)",
		"kind": "Materials",
		"credit": "Runtime rebinding of the existing registered normal maps onto fleet structure; no new image asset.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "Fleet readability palette (runtime scalar tints)",
		"kind": "Materials",
		"credit": "Hand-picked scalar hull and accent tints chosen for colour-vision separation; no image asset.",
		"licence": PROJECT_ORIGINAL,
	},
	{
		"register": "assets/materials/arrow-hull-albedo-v1.png",
		"kind": "Textures",
		"credit": "Ceramic-composite panel albedo for the Arrow recon craft.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/materials/torrent-hull-albedo-v1.png",
		"kind": "Textures",
		"credit": "Off-white panelled hull albedo for the Torrent.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/keth-nebula.png",
		"kind": "Images",
		"credit": "Panoramic deep-space backdrop used on the title screen and as faint sky cover.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/audio/combat/",
		"kind": "Sounds",
		"credit": "Seven combat one-shots from fixed-seed offline synthesis (tools/audio/generate_combat_audio_v1.py).",
		"licence": "Original procedural synthesis for Mudds Shipyards; no recorded, sampled or third-party sound.",
	},
	{
		"register": "assets/audio/combat/torpedo_run/",
		"kind": "Sounds",
		"credit": "Torpedo Run launch, lock, flight, intercept, detonation and board tones (tools/audio/generate_torpedo_run_audio.py).",
		"licence": "Original procedural synthesis for Mudds Shipyards; no recorded, sampled or third-party sound.",
	},
	{
		"register": "assets/audio/music/",
		"kind": "Music",
		"credit": "Station, flight and surface ambient music beds (tools/audio/generate_station_music_v1.py, tools/audio/generate_flight_music_v1.py).",
		"licence": "Original procedural synthesis for Mudds Shipyards; no recorded, sampled or third-party music.",
	},
	{
		"register": "assets/keth-icon.png",
		"kind": "Images",
		"credit": "Project and Windows application icon.",
		"licence": IMAGEGEN_ORIGINAL,
	},
	{
		"register": "assets/audio/music/combat_* — adaptive combat music layer v1",
		"kind": "Music",
		"credit": "Adaptive combat stems and victory/failure stingers (tools/audio/generate_combat_music.py, using numpy and scipy offline).",
		"licence": "Original procedural synthesis for Mudds Shipyards; no recorded, sampled or third-party music.",
	},
]

## Tools used to make the assets above. None of them ships with the game.
const TOOL_CREDITS: Array[Dictionary] = [
	{
		"name": "Godot Engine 4.7",
		"detail": "Game engine. Used under the MIT licence reproduced below.",
	},
	{
		"name": "Blender 4.0.2",
		"detail": "Authored the Zenith, central berth, Torrent and pilot model sources through the project's generator scripts in tools/blender/.",
	},
	{
		"name": "OpenAI image generation",
		"detail": "Produced the project-original texture, backdrop, concept and icon sources listed below.",
	},
	{
		"name": "Python, numpy and scipy",
		"detail": "Offline, fixed-seed synthesis of every sound effect and music bed.",
	},
]

const FONT_NOTE := "All interface text uses Godot Engine's built-in default font; its licence is listed in the Godot Engine third-party notices at the end of this page. The project bundles no other font."
const ORIGINS_NOTE := "An unofficial fan remake inspired by ZolarKeth's 2009 Roblox game Keth Shipyards. No original Roblox assets or scripts are bundled."
const ORIGINAL_WORK_NOTE := "All geometry, UI, effects and audio in the game are original project work. No original Roblox assets or scripts are bundled."


static func project_version() -> String:
	var version := str(ProjectSettings.get_setting("application/config/version", "")).strip_edges()
	return version if not version.is_empty() else "unknown"


## Footer line: game title, project version and, when known, the build stamp the
## pause menu already shows.
static func version_footer(build_display_text: String = "") -> String:
	var footer := "%s  //  VERSION %s" % [GAME_TITLE, project_version()]
	var build := build_display_text.strip_edges()
	if not build.is_empty():
		footer += "  //  %s" % build
	return footer


static func godot_version_text() -> String:
	var info := Engine.get_version_info()
	return "Godot Engine %s" % str(info.get("string", "%s.%s" % [
		str(info.get("major", 4)), str(info.get("minor", 0)),
	]))


## Godot's own MIT licence text, which the licence requires in the credits.
static func godot_license_text() -> String:
	return Engine.get_license_text().strip_edges()


## One entry per third-party component bundled inside the engine binary, as
## Engine.get_copyright_info() reports it: component name, copyright holders
## and the licence identifier.
static func engine_component_notices() -> Array[String]:
	var notices: Array[String] = []
	for raw_component: Variant in Engine.get_copyright_info():
		if not raw_component is Dictionary:
			continue
		var component := raw_component as Dictionary
		var lines: PackedStringArray = [str(component.get("name", "Component"))]
		for raw_part: Variant in component.get("parts", []):
			if not raw_part is Dictionary:
				continue
			var part := raw_part as Dictionary
			for holder: Variant in part.get("copyright", []):
				lines.append("  (c) %s" % str(holder))
			lines.append("  Licence: %s" % str(part.get("license", "")))
		notices.append("\n".join(lines))
	return notices


## The full text of every licence the engine components above refer to.
static func engine_license_texts() -> Array[String]:
	var texts: Array[String] = []
	var licenses := Engine.get_license_info()
	var names := licenses.keys()
	names.sort()
	for license_name: Variant in names:
		texts.append("%s\n\n%s" % [str(license_name), str(licenses[license_name]).strip_edges()])
	return texts


## The primary sections, in display order. The engine notices are a separate,
## collapsible section built on demand by the page.
static func sections() -> Array[Dictionary]:
	var asset_lines: Array[Dictionary] = []
	for entry: Dictionary in ASSET_ENTRIES:
		asset_lines.append({
			"heading": "%s  —  %s" % [str(entry.kind).to_upper(), str(entry.register)],
			"body": "%s\n%s" % [str(entry.credit), str(entry.licence)],
		})
	var tool_lines: Array[Dictionary] = []
	for tool: Dictionary in TOOL_CREDITS:
		tool_lines.append({"heading": str(tool.name), "body": str(tool.detail)})
	return [
		{
			"id": &"game",
			"title": GAME_TITLE,
			"entries": [
				{"heading": "Developed by", "body": "%s\n%s" % [TEAM_NAME, REPOSITORY]},
				{"heading": "Origins", "body": ORIGINS_NOTE},
			],
		},
		{
			"id": &"engine",
			"title": "ENGINE AND TOOLS",
			"entries": tool_lines,
		},
		{
			"id": &"godot_license",
			"title": "GODOT ENGINE LICENCE",
			"entries": [
				{"heading": godot_version_text(), "body": godot_license_text()},
			],
		},
		{
			"id": &"fonts",
			"title": "FONTS",
			"entries": [{"heading": "Interface font", "body": FONT_NOTE}],
		},
		{
			"id": &"assets",
			"title": "ASSET ATTRIBUTIONS AND LICENCES",
			"entries": asset_lines + [{"heading": "Original work", "body": ORIGINAL_WORK_NOTE}],
		},
	]


## Every registered ASSETS.md heading, for the page and its regression test.
static func asset_registers() -> PackedStringArray:
	var registers := PackedStringArray()
	for entry: Dictionary in ASSET_ENTRIES:
		registers.append(str(entry.register))
	return registers
